version: '3.8'

services:

  # Web Server Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  #Database Service
  db:
    image : mysql
    container_name : mysql
    volumes:
      - ./mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: password
  # db:
  #   image: postgres
  #   container_name: postgres
  #   volumes:
  #     - ./postgresql/data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   environment: 
  #     POSTGRES_DB: blog
  #     POSTGRES_USER: root 
  #     POSTGRES_PASSWORD: password 

  # Application Service
  app:
    container_name: blog
    build: 
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www
    ports:
      - "9000:9000"
    working_dir: /var/www
    depends_on:
      - node-app
    command: >
      sh -c "chown -R www-data:www-data /var/www/storage /var/www/bootstrap/cache && php-fpm"

  # Redis Service
  redis:
    container_name: redis
    image: redis
    ports:
      - "6380:6379"

  #phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "3400:80"
    depends_on:
      - db
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgAdmin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db 
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: hanieasemi76@gmail.com
  #     PGADMIN_DEFAULT_PASSWORD: password 

  # Node.js Service for npm commands
  # node-app:
  #   image: node:18
  #   container_name: node-app
  #   working_dir: /var/www
  #   volumes:
  #     - ./src:/var/www  # Sync the Laravel project folder
  #   command: >
  #     sh -c "npm install && npm run dev"  # Run npm install and then npm run dev
    
  node-app:
    image: node:18
    container_name: node-app
    working_dir: /var/www
    volumes:
      - ./src:/var/www
    command: >
      sh -c "npm install && npm run dev"
    depends_on:
      - db